# Generated by Django 2.0.8 on 2018-09-19 06:07

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showpage',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=zFSLbzEC76Y'),
            preserve_default=False,
        ),
    ]
