# Generated by Django 2.0.8 on 2018-09-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='date',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='date_event',
            field=models.CharField(default='1900-01-01', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='date_post',
            field=models.DateField(blank=True, default='1900-01-01', verbose_name='Event date'),
            preserve_default=False,
        ),
    ]
