# Generated by Django 2.0.8 on 2018-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180911_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='address',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
