# Generated by Django 2.0.8 on 2018-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_eventpage_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_event',
            field=models.CharField(max_length=250, verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date_post',
            field=models.DateField(blank=True, verbose_name='Posting Date'),
        ),
    ]
