# Generated by Django 2.0.8 on 2018-09-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180911_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='date_post',
            field=models.DateField(verbose_name='Posting Date'),
        ),
    ]
