#!/bin/sh

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
	if [ "develop" == "$branch" ]; then
		echo "Develop. Jenkins not setup yet."
	elif [ "master" == "$branch" ]; then
		echo "Master. Sending Jenkins build"
	curl -u jin:11cf2ecf36c8458239763fb4d6644110e8 https://jenkins.jinis.online/job/bodt-cms-master/build?token=qwerasdfzxcv-master
	fi

done

exit 0
