# Generated by Django 2.0.8 on 2018-09-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180904_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplepage',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
