# Generated by Django 2.2.3 on 2019-07-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180911_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
    ]
