# Generated by Django 2.2.3 on 2019-07-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_peoplepage_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='ordering_priority',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, null=True),
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='past',
            field=models.BooleanField(default=False),
        ),
    ]
