# Generated by Django 2.2.3 on 2019-07-27 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190727_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplepage',
            name='featured',
            field=models.BooleanField(default=False, help_text='Shows on the homepage'),
        ),
    ]
