# Generated by Django 2.2.3 on 2019-07-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190727_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplepage',
            old_name='past',
            new_name='alumni',
        ),
    ]
